# Updated : 2025.08.17
# Version : 1.1.4
# GitHub  : https://github.com/Sleeper85/esphome-packages

# This YAML is free software: you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation, either version 3
# of the License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
# See the GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program. If not, see <http://www.gnu.org/licenses/gpl.html>.

################################################################################

# If needed, configure a static IP here
# wifi:
#   manual_ip:
#     static_ip: 192.168.0.85
#     gateway: 192.168.0.1
#     subnet: 255.255.255.0
#     dns1: 8.8.8.8
#     dns2: 8.8.4.4

logger:
  level: DEBUG # VERBOSE / DEBUG / INFO / WARN

ota:
  platform: esphome
  
# Please use the native `api` component instead of the `mqtt` section.
# If you use Home Assistant, the native API is more lightweight.
# If there is no HA server connected to this API, the ESP32 reboots every 15 minutes to try to resolve the problem.
# The "reboot_timeout: 0s" option will keep your ESP32 up and running even if you lose connection to your HA server.
api:
  reboot_timeout: 0s

# If you don't want to use ESPHome's native API you can use MQTT instead.
# In this case don't forget to remove the 'api:' section.
# mqtt:
#   broker: !secret mqtt_host
#   username: !secret mqtt_username
#   password: !secret mqtt_password
#   id: mqtt_client

# Please note that enabling this component will take up a lot of memory and may decrease
# stability and be the cause of reboot depending on the capabilities of the board used.
# web_server:
#   port: 80
#   log: false
#   ota: false

# +--------------------------------------+
# | Global Settings                      |
# +--------------------------------------+
substitutions:
  # Name
  name: '' # Name that can be added as a second prefix after the friendly name, you can leave it blank.
  hostname: 'epever-node' # This is the name of the ESP32 node. It should always be unique in your ESPHome network.
  friendly_name : 'Epever' # Prefix added in front of all entity names and also to classify them.

# +--------------------------------------+
# | Packages                             |
# +--------------------------------------+
packages:

  ############### >>> UNCOMMENT YOUR BOARD <<< ###############
  ############### >>>   ONLY ONE BOARD !   <<< ###############

  board:
    url: https://github.com/Sleeper85/esphome-packages
    ref: main
    refresh: 0s
    files:
      - path: 'packages/board/board_ESP32_Generic.yaml'
      # - path: 'packages/board/board_ESP32_DevKit-V1.yaml'
      # - path: 'packages/board/board_ESP32_LilyGo-T-CAN485.yaml'
      # - path: 'packages/board/board_ESP32_EVB.yaml'
      # - path: 'packages/board/board_ESP32_Atom-Lite.yaml'
      # - path: 'packages/board/board_ESP32-C3_DevKitM-1.yaml'
      # - path: 'packages/board/board_ESP32-C3_ETH01-EVO.yaml'
      # - path: 'packages/board/board_ESP32-S3_DevKitC-1_LED-38.yaml'
      # - path: 'packages/board/board_ESP32-S3_DevKitC-1_LED-48.yaml'
      # - path: 'packages/board/board_ESP32-S3_LilyGo-T-Connect.yaml'
      # - path: 'packages/board/board_ESP32-S3_AtomS3-Lite.yaml'

      # - path: 'packages/board/board_ESP32-S3_AtomS3.yaml'
      #   vars:
      #     display_auto_next_page_interval: '5s'
      #     display_rotation: '0' # 0/90/180/270 rotation angle in degrees

      # - path: 'packages/board/board_ESP32-S3_AtomS3R.yaml'
      #   vars:
      #     display_auto_next_page_interval: '5s'
      #     display_rotation: '0' # 0/90/180/270 rotation angle in degrees

  ########### >>> UNCOMMENT YOUR BOARD OPTIONS <<< ###########

  board_options:
    url: https://github.com/Sleeper85/esphome-packages
    ref: main
    refresh: 0s
    files:
      # UART 1
      - path: 'packages/board/board_options_itf_uart_esp_1.yaml'
      # UART 2
      # - path: 'packages/board/board_options_itf_uart_esp_2.yaml'
      # UART 3
      # - path: 'packages/board/board_options_itf_uart_esp_3.yaml'

      # ESP32_CAN (TJA105x, SN65HVD230, M5Stack CAN base/unit)
      # - path: 'packages/board/board_options_itf_canbus_esp32_can.yaml'
      #   vars:
      #     canbus_node_id: 'canbus_node_1'
      
      # MCP2515
      # - path: 'packages/board/board_options_itf_canbus_mcp2515.yaml'
      #   vars:
      #     canbus_node_id: 'canbus_node_2'

  ############################################################

  modbus:
    url: https://github.com/Sleeper85/esphome-packages
    ref: main
    refresh: 0s
    files:
      - path: 'packages/base/device_modbus.yaml'
        vars:
          modbus_id: 'epever_modbus'
          modbus_role: 'client' # client / server
          modbus_uart_id: 'uart_esp_1' # RS485 board
          modbus_baud_rate: '115200' # 9600 / 19200 / 11520
          modbus_send_wait_time: '250ms' # time in milliseconds before the next ModBUS command is sent if an answer from a previous command is pending

  epever_scc:
    url: https://github.com/Sleeper85/esphome-packages
    ref: main
    refresh: 0s
    files:
      - path: 'packages/solar_charge_controller/epever/epever_scc_full.yaml'
        vars:
          scc_id: 'scc_1'                                           # ID
          scc_name: 'SCC 1'                                         # Name
          scc_modbus_id: 'epever_modbus'
          scc_modbus_address: '1'
          scc_modbus_throttle: '0ms'
          scc_update_interval: '5s'
          scc_input_number_mode: 'box'                              # box / slider
          scc_skip_updates_1: "30"                                  # 30s
          scc_skip_updates_2: "300"                                 # 5min
          # When the battery type is "USE" the Lithium battery voltage parameters follow the following logic :
          # A. Over Voltage Disconnect Voltage > Over Charging Protection Voltage (BMS)+0.2V
          # B. Over Voltage Disconnect Voltage > Over Voltage Reconnect Voltage = Charging Limit Voltage
          #    ≥ Equalize Charging Voltage = Boost Charging Voltage ≥ Float Charging Voltage > Boost Reconnect Charging Voltage
          # C. Low Voltage Reconnect Voltage > Low Voltage Disconnect Voltage ≥ Discharging Limit Voltage
          # D. Under Voltage Alarm Reconnect Voltage > Under Voltage Alarm Voltage ≥ Discharging Limit Voltage
          # E. Boost Reconnect Charging voltage > Low Voltage Reconnect Voltage
          # F. Low Voltage Disconnect Voltage ≥ Discharging Limit Voltage (BMS)+0.2V
          scc_overvoltage_disconnect_voltage: '29.0'                # 3.625V/cell
          scc_charging_limit_voltage: '28.0'                        # 3.5V/cell
          scc_overvoltage_reconnect_voltage: '28.0'                 # 3.5V/cell
          scc_equalization_charging_voltage: '27.6'                 # 3.45V/cell
          scc_boost_charging_voltage: '27.6'                        # 3.45V/cell
          scc_float_charging_voltage: '27.0'                        # 3.375V/cell
          scc_boost_reconnect_charging_voltage: '26.4'              # 3.3V/cell
          scc_low_voltage_reconnect_voltage: '25.0'                 # 3.125V/cell
          scc_undervoltage_alarm_recovery_voltage: '25.0'           # 3.125V/cell
          scc_undervoltage_alarm_voltage: '24.8'                    # 3.1V/cell
          scc_low_voltage_disconnect_voltage: '24.0'                # 3.0V/cell
          scc_discharging_limit_voltage: '22.4'                     # 2.8V/cell

  # +--------------------------------------+
  # | DEBUG ( logger level must be DEBUG ) |
  # +--------------------------------------+

  debug:
    url: https://github.com/Sleeper85/esphome-packages
    ref: main
    refresh: 0s
    files:
      - path: 'packages/base/device_debug_ESP32.yaml'
        vars:
          debug_name: 'Debug'
          debug_update_interval: '5s'
