# Updated : 2025.06.02
# Version : 1.1.1
# GitHub  : https://github.com/Sleeper85/esphome-packages

# This YAML is free software: you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation, either version 3
# of the License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
# See the GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program. If not, see <http://www.gnu.org/licenses/gpl.html>.

sensor:
  # +--------------------------------------+
  # | Total Daily Energy                   |
  # +--------------------------------------+
  - platform: total_daily_energy
    name: "${inverter_name} Daily Load Output Energy"
    power_id: inverter_load_output_power
    unit_of_measurement: 'kWh'
    state_class: total_increasing
    device_class: energy
    accuracy_decimals: 3
    filters:
      # Multiplication factor from W to kW is 0.001
      - multiply: 0.001

  # +--------------------------------------+
  # | Inverter                             |
  # +--------------------------------------+
  - platform: modbus_controller
    modbus_controller_id: modbus_controller_1
    name: "${inverter_name} Load Input Voltage"
    address: 0x3108
    value_type: U_WORD
    register_type: read
    device_class: "voltage"
    state_class: "measurement"
    unit_of_measurement: "V"
    accuracy_decimals: 2
    filters:
      - multiply: 0.01
    
  - platform: modbus_controller
    modbus_controller_id: modbus_controller_1
    name: "${inverter_name} Load Input Current"
    address: 0x3109
    value_type: U_WORD
    register_type: read
    device_class: "current"
    state_class: "measurement"
    unit_of_measurement: "A"
    accuracy_decimals: 2
    filters:
      - multiply: 0.01
    
  - platform: modbus_controller
    modbus_controller_id: modbus_controller_1
    name: "${inverter_name} Load Input Power"
    address: 0x310A
    value_type: U_DWORD_R
    register_type: read
    device_class: "power"
    state_class: "measurement"
    unit_of_measurement: "W"
    accuracy_decimals: 2
    filters:
      - multiply: 0.01
    
  - platform: modbus_controller
    modbus_controller_id: modbus_controller_1
    name: "${inverter_name} Load Output Voltage"
    address: 0x310C
    value_type: U_WORD
    register_type: read
    device_class: "voltage"
    state_class: "measurement"
    unit_of_measurement: "V"
    accuracy_decimals: 2
    filters:
      - multiply: 0.01
    
  - platform: modbus_controller
    modbus_controller_id: modbus_controller_1
    name: "${inverter_name} Load Output Current"
    address: 0x310D
    value_type: U_WORD
    register_type: read
    device_class: "current"
    state_class: "measurement"
    unit_of_measurement: "A"
    accuracy_decimals: 2
    filters:
      - multiply: 0.01
    
  - platform: modbus_controller
    modbus_controller_id: modbus_controller_1
    name: "${inverter_name} Load Output Power"
    id: "inverter_load_output_power"
    address: 0x310E
    value_type: U_DWORD_R
    register_type: read
    device_class: "power"
    state_class: "measurement"
    unit_of_measurement: "W"
    accuracy_decimals: 2
    filters:
      - multiply: 0.01

  - platform: modbus_controller
    modbus_controller_id: modbus_controller_1
    name: "${inverter_name} Device Temperature"
    address: 0x3111
    value_type: S_WORD
    register_type: read
    device_class: "temperature"
    state_class: "measurement"
    unit_of_measurement: "°C"
    accuracy_decimals: 1
    filters:
      - multiply: 0.01

  - platform: modbus_controller
    modbus_controller_id: modbus_controller_1
    name: "${inverter_name} Heak Sink Temperature"
    address: 0x3112
    value_type: S_WORD
    register_type: read
    device_class: "temperature"
    state_class: "measurement"
    unit_of_measurement: "°C"
    accuracy_decimals: 1
    filters:
      - multiply: 0.01

  - platform: modbus_controller
    modbus_controller_id: modbus_controller_1
    name: "${inverter_name} Load status"
    id: "load_status_raw_value"
    address: 0x3202
    value_type: U_WORD
    register_type: read

switch:
  # +--------------------------------------+
  # | Inverter                             |
  # +--------------------------------------+
  - platform: modbus_controller
    modbus_controller_id: modbus_controller_1
    name: "${inverter_name} Control Local-Remote"
    entity_category: config
    address: 0x11
    register_type: coil
    bitmask: 0x01

  - platform: modbus_controller
    modbus_controller_id: modbus_controller_1
    name: "${inverter_name} Inverter OFF-ON"
    entity_category: config
    address: 0xF
    register_type: coil
    bitmask: 0x01
    
  - platform: modbus_controller
    modbus_controller_id: modbus_controller_1
    name: "${inverter_name} Power saving OFF-ON"
    entity_category: config
    address: 0x4
    register_type: coil
    bitmask: 0x01
